/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Woody's Games (https://sketchfab.com/woodysgames)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/paper-airplane-4c8336e584e54766aa726ea29c9dd1d6
Title: Paper Airplane
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
  };
  materials: {
    ["Scene_-_Root"]: THREE.MeshStandardMaterial;
  };
};

const gltfUrl = "./paperPlane/scene.gltf";

export function PaperPlane(
  props: JSX.IntrinsicElements["group"] & { showAxes?: boolean },
) {
  const { nodes, materials } = useGLTF(gltfUrl) as GLTFResult;
  const { showAxes = false, ...rest } = props;
  return (
    <group {...rest} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[Math.PI / 2, 0, 0]}
      />

      {showAxes && <axesHelper />}
    </group>
  );
}

useGLTF.preload(gltfUrl);
